
name: Daily Washington DC Image Fetch

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  fetch-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run image fetcher
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python dc_image_fetcher.py

      - name: Commit and Push Image
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add images/
          git commit -m "Daily image update $(date +'%Y-%m-%d')" || echo "No changes"
          git push
